eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8585/realms/turkcell-library-p1-dev
  datasource:
    url: jdbc:postgresql://localhost:5433/book_service
    username: postgres
    password: book_service_db_password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  kafka:
    bootstrap-servers: localhost:9094
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9094
      bindings:
        orderCreated-in-0:
          destination: book-topic
          group: book-service
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
