eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8585/realms/turkcell-library-p1-dev
  datasource:
    url: jdbc:postgresql://localhost:5433/book_service
    username: postgres
    password: book_service_db_password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  kafka:
    bootstrap-servers: localhost:9094
  cloud:
    function:
      definition: loanEvents
    stream:
      kafka:
        binder:
          brokers: localhost:9094
      bindings:
        bookCreated-out-0:
          destination: book-topic
        loanEvents-in-0:
          destination: loan-events-topic # Loan Service'in yayınladığı Topic adı ile BİREBİR EŞLEŞMELİ
          group: book-status-updater-group
          contentType: application/json
          consumer:
            enableDlq: true
            auto-offset-reset: earliest
            maxAttempts: 3
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
