eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  kafka:
    bootstrap-servers: localhost:9094
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9094
      bindings:
        bookCreated-in-0:
          destination: book-topic
          contentType: application/json
          group: book-service


  datasource:
    url: jdbc:postgresql://localhost:5436/author_service
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: author_service_db_password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
