eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  kafka:
    bootstrap-servers: localhost:9094
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9094
      bindings:
        bookCreated-in-0:
          destination: book-topic
          contentType: application/json
          group: publisher-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8585/realms/turkcell-library-p1-dev

  datasource:
    url: jdbc:postgresql://localhost:5437/publisher_service
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: publisher_service_db_password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
